version: '3.8'
services:
  app:
    build:
      context: .
    container_name: rails_app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
    env_file:
      - .env
    depends_on:
      - redis

  sidekiq:
    build:
      context: .
    container_name: sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - .:/app
    depends_on:
      - app
      - redis
    environment:
      RAILS_ENV: production
      REDIS_URL: ${REDIS_URL}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}

    env_file:
      - .env
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
